[package]
name = "msg"
version = "0.1.0"
edition = "2021"
authors = ["Israel Bermudez Sepulveda <israel.bermudez@proton.me>"]
license = "Apache-2.0"

[dependencies]
finch = { path = "../finch" }
serde = "1.0.208"
sonic-rs = "0.3.11"
clap = { version = "4.5.16", features = ["derive", "env" ] }

